from __future__ import annotations


class ChallengeNotFound(Exception): ...


class CredentialNotFound(Exception): ...


class CredentialMutationDenied(Exception): ...


class UserHandleMismatch(Exception): ...


class PasskeyUserConflict(Exception): ...


class PasskeyCredentialConflict(Exception): ...


class CredentialCounterConflict(Exception): ...
